//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaragesClient.ServiceWebAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web/", ConfigurationName="ServiceWebAPI.GarageWebAPI")]
    public interface GarageWebAPI {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/updateOwnerRequest", ReplyAction="http://web/GarageWebAPI/updateOwnerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.updateOwnerResponse updateOwner(GaragesClient.ServiceWebAPI.updateOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/updateOwnerRequest", ReplyAction="http://web/GarageWebAPI/updateOwnerResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateOwnerResponse> updateOwnerAsync(GaragesClient.ServiceWebAPI.updateOwnerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/garagesDetailsInfoRequest", ReplyAction="http://web/GarageWebAPI/garagesDetailsInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.garagesDetailsInfoResponse garagesDetailsInfo(GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/garagesDetailsInfoRequest", ReplyAction="http://web/GarageWebAPI/garagesDetailsInfoResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.garagesDetailsInfoResponse> garagesDetailsInfoAsync(GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/getFilterInfoTotalRequest", ReplyAction="http://web/GarageWebAPI/getFilterInfoTotalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.getFilterInfoTotalResponse getFilterInfoTotal(GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/getFilterInfoTotalRequest", ReplyAction="http://web/GarageWebAPI/getFilterInfoTotalResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.getFilterInfoTotalResponse> getFilterInfoTotalAsync(GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findGarageByIdRequest", ReplyAction="http://web/GarageWebAPI/findGarageByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.findGarageByIdResponse findGarageById(GaragesClient.ServiceWebAPI.findGarageByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findGarageByIdRequest", ReplyAction="http://web/GarageWebAPI/findGarageByIdResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findGarageByIdResponse> findGarageByIdAsync(GaragesClient.ServiceWebAPI.findGarageByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteAllGaragesRequest", ReplyAction="http://web/GarageWebAPI/deleteAllGaragesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteAllGarages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteAllGaragesRequest", ReplyAction="http://web/GarageWebAPI/deleteAllGaragesResponse")]
        System.Threading.Tasks.Task deleteAllGaragesAsync();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findCarByIdRequest", ReplyAction="http://web/GarageWebAPI/findCarByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.findCarByIdResponse findCarById(GaragesClient.ServiceWebAPI.findCarByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findCarByIdRequest", ReplyAction="http://web/GarageWebAPI/findCarByIdResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findCarByIdResponse> findCarByIdAsync(GaragesClient.ServiceWebAPI.findCarByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findAllCarsRequest", ReplyAction="http://web/GarageWebAPI/findAllCarsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.findAllCarsResponse findAllCars(GaragesClient.ServiceWebAPI.findAllCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findAllCarsRequest", ReplyAction="http://web/GarageWebAPI/findAllCarsResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllCarsResponse> findAllCarsAsync(GaragesClient.ServiceWebAPI.findAllCarsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/updateCarRequest", ReplyAction="http://web/GarageWebAPI/updateCarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.updateCarResponse updateCar(GaragesClient.ServiceWebAPI.updateCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/updateCarRequest", ReplyAction="http://web/GarageWebAPI/updateCarResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateCarResponse> updateCarAsync(GaragesClient.ServiceWebAPI.updateCarRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteCarByIdRequest", ReplyAction="http://web/GarageWebAPI/deleteCarByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GaragesClient.ServiceWebAPI.deleteCarByIdResponse deleteCarById(GaragesClient.ServiceWebAPI.deleteCarByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteCarByIdRequest", ReplyAction="http://web/GarageWebAPI/deleteCarByIdResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteCarByIdResponse> deleteCarByIdAsync(GaragesClient.ServiceWebAPI.deleteCarByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteAllCarsRequest", ReplyAction="http://web/GarageWebAPI/deleteAllCarsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteAllCarsRequest", ReplyAction="http://web/GarageWebAPI/deleteAllCarsResponse")]
        System.Threading.Tasks.Task deleteAllCarsAsync();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/persistOwnerRequest", ReplyAction="http://web/GarageWebAPI/persistOwnerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.persistOwnerResponse persistOwner(GaragesClient.ServiceWebAPI.persistOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/persistOwnerRequest", ReplyAction="http://web/GarageWebAPI/persistOwnerResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistOwnerResponse> persistOwnerAsync(GaragesClient.ServiceWebAPI.persistOwnerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findOwnerByIdRequest", ReplyAction="http://web/GarageWebAPI/findOwnerByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.findOwnerByIdResponse findOwnerById(GaragesClient.ServiceWebAPI.findOwnerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findOwnerByIdRequest", ReplyAction="http://web/GarageWebAPI/findOwnerByIdResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findOwnerByIdResponse> findOwnerByIdAsync(GaragesClient.ServiceWebAPI.findOwnerByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findAllOwnersRequest", ReplyAction="http://web/GarageWebAPI/findAllOwnersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.findAllOwnersResponse findAllOwners(GaragesClient.ServiceWebAPI.findAllOwnersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findAllOwnersRequest", ReplyAction="http://web/GarageWebAPI/findAllOwnersResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllOwnersResponse> findAllOwnersAsync(GaragesClient.ServiceWebAPI.findAllOwnersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findAllGaragesRequest", ReplyAction="http://web/GarageWebAPI/findAllGaragesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.findAllGaragesResponse findAllGarages(GaragesClient.ServiceWebAPI.findAllGaragesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/findAllGaragesRequest", ReplyAction="http://web/GarageWebAPI/findAllGaragesResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllGaragesResponse> findAllGaragesAsync(GaragesClient.ServiceWebAPI.findAllGaragesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/updateGarageRequest", ReplyAction="http://web/GarageWebAPI/updateGarageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.updateGarageResponse updateGarage(GaragesClient.ServiceWebAPI.updateGarageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/updateGarageRequest", ReplyAction="http://web/GarageWebAPI/updateGarageResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateGarageResponse> updateGarageAsync(GaragesClient.ServiceWebAPI.updateGarageRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/persistCarRequest", ReplyAction="http://web/GarageWebAPI/persistCarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.persistCarResponse persistCar(GaragesClient.ServiceWebAPI.persistCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/persistCarRequest", ReplyAction="http://web/GarageWebAPI/persistCarResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistCarResponse> persistCarAsync(GaragesClient.ServiceWebAPI.persistCarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/persistGarageRequest", ReplyAction="http://web/GarageWebAPI/persistGarageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.persistGarageResponse persistGarage(GaragesClient.ServiceWebAPI.persistGarageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/persistGarageRequest", ReplyAction="http://web/GarageWebAPI/persistGarageResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistGarageResponse> persistGarageAsync(GaragesClient.ServiceWebAPI.persistGarageRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteGarageByIdRequest", ReplyAction="http://web/GarageWebAPI/deleteGarageByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GaragesClient.ServiceWebAPI.deleteGarageByIdResponse deleteGarageById(GaragesClient.ServiceWebAPI.deleteGarageByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteGarageByIdRequest", ReplyAction="http://web/GarageWebAPI/deleteGarageByIdResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteGarageByIdResponse> deleteGarageByIdAsync(GaragesClient.ServiceWebAPI.deleteGarageByIdRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteOwnerByIdRequest", ReplyAction="http://web/GarageWebAPI/deleteOwnerByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GaragesClient.ServiceWebAPI.deleteOwnerByIdResponse deleteOwnerById(GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteOwnerByIdRequest", ReplyAction="http://web/GarageWebAPI/deleteOwnerByIdResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteOwnerByIdResponse> deleteOwnerByIdAsync(GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/getInfoTotalRequest", ReplyAction="http://web/GarageWebAPI/getInfoTotalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GaragesClient.ServiceWebAPI.getInfoTotalResponse getInfoTotal(GaragesClient.ServiceWebAPI.getInfoTotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/getInfoTotalRequest", ReplyAction="http://web/GarageWebAPI/getInfoTotalResponse")]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.getInfoTotalResponse> getInfoTotalAsync(GaragesClient.ServiceWebAPI.getInfoTotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteAllOwnersRequest", ReplyAction="http://web/GarageWebAPI/deleteAllOwnersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteAllOwners();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/GarageWebAPI/deleteAllOwnersRequest", ReplyAction="http://web/GarageWebAPI/deleteAllOwnersResponse")]
        System.Threading.Tasks.Task deleteAllOwnersAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web/")]
    public partial class ownerDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private carDto[] carsField;
        
        private string contactPhoneField;
        
        private string firstNameField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cars", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public carDto[] cars {
            get {
                return this.carsField;
            }
            set {
                this.carsField = value;
                this.RaisePropertyChanged("cars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contactPhone {
            get {
                return this.contactPhoneField;
            }
            set {
                this.contactPhoneField = value;
                this.RaisePropertyChanged("contactPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web/")]
    public partial class carDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long garageIdField;
        
        private bool garageIdFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private int kilometrageField;
        
        private bool kilometrageFieldSpecified;
        
        private string modelField;
        
        private long ownerIdField;
        
        private bool ownerIdFieldSpecified;
        
        private string registrationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long garageId {
            get {
                return this.garageIdField;
            }
            set {
                this.garageIdField = value;
                this.RaisePropertyChanged("garageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool garageIdSpecified {
            get {
                return this.garageIdFieldSpecified;
            }
            set {
                this.garageIdFieldSpecified = value;
                this.RaisePropertyChanged("garageIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int kilometrage {
            get {
                return this.kilometrageField;
            }
            set {
                this.kilometrageField = value;
                this.RaisePropertyChanged("kilometrage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kilometrageSpecified {
            get {
                return this.kilometrageFieldSpecified;
            }
            set {
                this.kilometrageFieldSpecified = value;
                this.RaisePropertyChanged("kilometrageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long ownerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
                this.RaisePropertyChanged("ownerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ownerIdSpecified {
            get {
                return this.ownerIdFieldSpecified;
            }
            set {
                this.ownerIdFieldSpecified = value;
                this.RaisePropertyChanged("ownerIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string registrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
                this.RaisePropertyChanged("registrationNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web/")]
    public partial class infoTotalDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string carModelField;
        
        private string carRegistrationNumberField;
        
        private string garageAddressField;
        
        private string garageSerialNumberField;
        
        private string ownerFirstNameField;
        
        private string ownerLastNameField;
        
        private string ownerPhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string carModel {
            get {
                return this.carModelField;
            }
            set {
                this.carModelField = value;
                this.RaisePropertyChanged("carModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string carRegistrationNumber {
            get {
                return this.carRegistrationNumberField;
            }
            set {
                this.carRegistrationNumberField = value;
                this.RaisePropertyChanged("carRegistrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string garageAddress {
            get {
                return this.garageAddressField;
            }
            set {
                this.garageAddressField = value;
                this.RaisePropertyChanged("garageAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string garageSerialNumber {
            get {
                return this.garageSerialNumberField;
            }
            set {
                this.garageSerialNumberField = value;
                this.RaisePropertyChanged("garageSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ownerFirstName {
            get {
                return this.ownerFirstNameField;
            }
            set {
                this.ownerFirstNameField = value;
                this.RaisePropertyChanged("ownerFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ownerLastName {
            get {
                return this.ownerLastNameField;
            }
            set {
                this.ownerLastNameField = value;
                this.RaisePropertyChanged("ownerLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ownerPhoneNumber {
            get {
                return this.ownerPhoneNumberField;
            }
            set {
                this.ownerPhoneNumberField = value;
                this.RaisePropertyChanged("ownerPhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web/")]
    public partial class garageDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private carDto[] carsField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private int maxCarsField;
        
        private bool maxCarsFieldSpecified;
        
        private string serialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cars", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public carDto[] cars {
            get {
                return this.carsField;
            }
            set {
                this.carsField = value;
                this.RaisePropertyChanged("cars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int maxCars {
            get {
                return this.maxCarsField;
            }
            set {
                this.maxCarsField = value;
                this.RaisePropertyChanged("maxCars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxCarsSpecified {
            get {
                return this.maxCarsFieldSpecified;
            }
            set {
                this.maxCarsFieldSpecified = value;
                this.RaisePropertyChanged("maxCarsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("serialNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOwner", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class updateOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.ownerDto arg0;
        
        public updateOwnerRequest() {
        }
        
        public updateOwnerRequest(GaragesClient.ServiceWebAPI.ownerDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOwnerResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class updateOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public updateOwnerResponse() {
        }
        
        public updateOwnerResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="garagesDetailsInfo", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class garagesDetailsInfoRequest {
        
        public garagesDetailsInfoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="garagesDetailsInfoResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class garagesDetailsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.garageDto[] @return;
        
        public garagesDetailsInfoResponse() {
        }
        
        public garagesDetailsInfoResponse(GaragesClient.ServiceWebAPI.garageDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFilterInfoTotal", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getFilterInfoTotalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public getFilterInfoTotalRequest() {
        }
        
        public getFilterInfoTotalRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFilterInfoTotalResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getFilterInfoTotalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.infoTotalDto[] @return;
        
        public getFilterInfoTotalResponse() {
        }
        
        public getFilterInfoTotalResponse(GaragesClient.ServiceWebAPI.infoTotalDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findGarageById", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findGarageByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findGarageByIdRequest() {
        }
        
        public findGarageByIdRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findGarageByIdResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findGarageByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.garageDto @return;
        
        public findGarageByIdResponse() {
        }
        
        public findGarageByIdResponse(GaragesClient.ServiceWebAPI.garageDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCarById", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findCarByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findCarByIdRequest() {
        }
        
        public findCarByIdRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCarByIdResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findCarByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.carDto @return;
        
        public findCarByIdResponse() {
        }
        
        public findCarByIdResponse(GaragesClient.ServiceWebAPI.carDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllCars", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findAllCarsRequest {
        
        public findAllCarsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllCarsResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findAllCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.carDto[] @return;
        
        public findAllCarsResponse() {
        }
        
        public findAllCarsResponse(GaragesClient.ServiceWebAPI.carDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCar", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class updateCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.carDto arg0;
        
        public updateCarRequest() {
        }
        
        public updateCarRequest(GaragesClient.ServiceWebAPI.carDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCarResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class updateCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public updateCarResponse() {
        }
        
        public updateCarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCarById", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class deleteCarByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public deleteCarByIdRequest() {
        }
        
        public deleteCarByIdRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCarByIdResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class deleteCarByIdResponse {
        
        public deleteCarByIdResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="persistOwner", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class persistOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.ownerDto arg0;
        
        public persistOwnerRequest() {
        }
        
        public persistOwnerRequest(GaragesClient.ServiceWebAPI.ownerDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="persistOwnerResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class persistOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public persistOwnerResponse() {
        }
        
        public persistOwnerResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOwnerById", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findOwnerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findOwnerByIdRequest() {
        }
        
        public findOwnerByIdRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOwnerByIdResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findOwnerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.ownerDto @return;
        
        public findOwnerByIdResponse() {
        }
        
        public findOwnerByIdResponse(GaragesClient.ServiceWebAPI.ownerDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllOwners", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findAllOwnersRequest {
        
        public findAllOwnersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllOwnersResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findAllOwnersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.ownerDto[] @return;
        
        public findAllOwnersResponse() {
        }
        
        public findAllOwnersResponse(GaragesClient.ServiceWebAPI.ownerDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllGarages", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findAllGaragesRequest {
        
        public findAllGaragesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllGaragesResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class findAllGaragesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.garageDto[] @return;
        
        public findAllGaragesResponse() {
        }
        
        public findAllGaragesResponse(GaragesClient.ServiceWebAPI.garageDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateGarage", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class updateGarageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.garageDto arg0;
        
        public updateGarageRequest() {
        }
        
        public updateGarageRequest(GaragesClient.ServiceWebAPI.garageDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateGarageResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class updateGarageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public updateGarageResponse() {
        }
        
        public updateGarageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="persistCar", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class persistCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.carDto arg0;
        
        public persistCarRequest() {
        }
        
        public persistCarRequest(GaragesClient.ServiceWebAPI.carDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="persistCarResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class persistCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public persistCarResponse() {
        }
        
        public persistCarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="persistGarage", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class persistGarageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.garageDto arg0;
        
        public persistGarageRequest() {
        }
        
        public persistGarageRequest(GaragesClient.ServiceWebAPI.garageDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="persistGarageResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class persistGarageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public persistGarageResponse() {
        }
        
        public persistGarageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteGarageById", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class deleteGarageByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public deleteGarageByIdRequest() {
        }
        
        public deleteGarageByIdRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteGarageByIdResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class deleteGarageByIdResponse {
        
        public deleteGarageByIdResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteOwnerById", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class deleteOwnerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public deleteOwnerByIdRequest() {
        }
        
        public deleteOwnerByIdRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteOwnerByIdResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class deleteOwnerByIdResponse {
        
        public deleteOwnerByIdResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoTotal", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getInfoTotalRequest {
        
        public getInfoTotalRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoTotalResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getInfoTotalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GaragesClient.ServiceWebAPI.infoTotalDto[] @return;
        
        public getInfoTotalResponse() {
        }
        
        public getInfoTotalResponse(GaragesClient.ServiceWebAPI.infoTotalDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GarageWebAPIChannel : GaragesClient.ServiceWebAPI.GarageWebAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GarageWebAPIClient : System.ServiceModel.ClientBase<GaragesClient.ServiceWebAPI.GarageWebAPI>, GaragesClient.ServiceWebAPI.GarageWebAPI {
        
        public GarageWebAPIClient() {
        }
        
        public GarageWebAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GarageWebAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarageWebAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarageWebAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.updateOwnerResponse GaragesClient.ServiceWebAPI.GarageWebAPI.updateOwner(GaragesClient.ServiceWebAPI.updateOwnerRequest request) {
            return base.Channel.updateOwner(request);
        }
        
        public string updateOwner(GaragesClient.ServiceWebAPI.ownerDto arg0) {
            GaragesClient.ServiceWebAPI.updateOwnerRequest inValue = new GaragesClient.ServiceWebAPI.updateOwnerRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.updateOwnerResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).updateOwner(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateOwnerResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.updateOwnerAsync(GaragesClient.ServiceWebAPI.updateOwnerRequest request) {
            return base.Channel.updateOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateOwnerResponse> updateOwnerAsync(GaragesClient.ServiceWebAPI.ownerDto arg0) {
            GaragesClient.ServiceWebAPI.updateOwnerRequest inValue = new GaragesClient.ServiceWebAPI.updateOwnerRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).updateOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.garagesDetailsInfoResponse GaragesClient.ServiceWebAPI.GarageWebAPI.garagesDetailsInfo(GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest request) {
            return base.Channel.garagesDetailsInfo(request);
        }
        
        public GaragesClient.ServiceWebAPI.garageDto[] garagesDetailsInfo() {
            GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest inValue = new GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest();
            GaragesClient.ServiceWebAPI.garagesDetailsInfoResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).garagesDetailsInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.garagesDetailsInfoResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.garagesDetailsInfoAsync(GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest request) {
            return base.Channel.garagesDetailsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.garagesDetailsInfoResponse> garagesDetailsInfoAsync() {
            GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest inValue = new GaragesClient.ServiceWebAPI.garagesDetailsInfoRequest();
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).garagesDetailsInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.getFilterInfoTotalResponse GaragesClient.ServiceWebAPI.GarageWebAPI.getFilterInfoTotal(GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest request) {
            return base.Channel.getFilterInfoTotal(request);
        }
        
        public GaragesClient.ServiceWebAPI.infoTotalDto[] getFilterInfoTotal(string arg0, string arg1, string arg2, string arg3) {
            GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest inValue = new GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            GaragesClient.ServiceWebAPI.getFilterInfoTotalResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).getFilterInfoTotal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.getFilterInfoTotalResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.getFilterInfoTotalAsync(GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest request) {
            return base.Channel.getFilterInfoTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.getFilterInfoTotalResponse> getFilterInfoTotalAsync(string arg0, string arg1, string arg2, string arg3) {
            GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest inValue = new GaragesClient.ServiceWebAPI.getFilterInfoTotalRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).getFilterInfoTotalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.findGarageByIdResponse GaragesClient.ServiceWebAPI.GarageWebAPI.findGarageById(GaragesClient.ServiceWebAPI.findGarageByIdRequest request) {
            return base.Channel.findGarageById(request);
        }
        
        public GaragesClient.ServiceWebAPI.garageDto findGarageById(long arg0) {
            GaragesClient.ServiceWebAPI.findGarageByIdRequest inValue = new GaragesClient.ServiceWebAPI.findGarageByIdRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.findGarageByIdResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findGarageById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findGarageByIdResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.findGarageByIdAsync(GaragesClient.ServiceWebAPI.findGarageByIdRequest request) {
            return base.Channel.findGarageByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findGarageByIdResponse> findGarageByIdAsync(long arg0) {
            GaragesClient.ServiceWebAPI.findGarageByIdRequest inValue = new GaragesClient.ServiceWebAPI.findGarageByIdRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findGarageByIdAsync(inValue);
        }
        
        public void deleteAllGarages() {
            base.Channel.deleteAllGarages();
        }
        
        public System.Threading.Tasks.Task deleteAllGaragesAsync() {
            return base.Channel.deleteAllGaragesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.findCarByIdResponse GaragesClient.ServiceWebAPI.GarageWebAPI.findCarById(GaragesClient.ServiceWebAPI.findCarByIdRequest request) {
            return base.Channel.findCarById(request);
        }
        
        public GaragesClient.ServiceWebAPI.carDto findCarById(long arg0) {
            GaragesClient.ServiceWebAPI.findCarByIdRequest inValue = new GaragesClient.ServiceWebAPI.findCarByIdRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.findCarByIdResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findCarById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findCarByIdResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.findCarByIdAsync(GaragesClient.ServiceWebAPI.findCarByIdRequest request) {
            return base.Channel.findCarByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findCarByIdResponse> findCarByIdAsync(long arg0) {
            GaragesClient.ServiceWebAPI.findCarByIdRequest inValue = new GaragesClient.ServiceWebAPI.findCarByIdRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findCarByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.findAllCarsResponse GaragesClient.ServiceWebAPI.GarageWebAPI.findAllCars(GaragesClient.ServiceWebAPI.findAllCarsRequest request) {
            return base.Channel.findAllCars(request);
        }
        
        public GaragesClient.ServiceWebAPI.carDto[] findAllCars() {
            GaragesClient.ServiceWebAPI.findAllCarsRequest inValue = new GaragesClient.ServiceWebAPI.findAllCarsRequest();
            GaragesClient.ServiceWebAPI.findAllCarsResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findAllCars(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllCarsResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.findAllCarsAsync(GaragesClient.ServiceWebAPI.findAllCarsRequest request) {
            return base.Channel.findAllCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllCarsResponse> findAllCarsAsync() {
            GaragesClient.ServiceWebAPI.findAllCarsRequest inValue = new GaragesClient.ServiceWebAPI.findAllCarsRequest();
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findAllCarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.updateCarResponse GaragesClient.ServiceWebAPI.GarageWebAPI.updateCar(GaragesClient.ServiceWebAPI.updateCarRequest request) {
            return base.Channel.updateCar(request);
        }
        
        public string updateCar(GaragesClient.ServiceWebAPI.carDto arg0) {
            GaragesClient.ServiceWebAPI.updateCarRequest inValue = new GaragesClient.ServiceWebAPI.updateCarRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.updateCarResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).updateCar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateCarResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.updateCarAsync(GaragesClient.ServiceWebAPI.updateCarRequest request) {
            return base.Channel.updateCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateCarResponse> updateCarAsync(GaragesClient.ServiceWebAPI.carDto arg0) {
            GaragesClient.ServiceWebAPI.updateCarRequest inValue = new GaragesClient.ServiceWebAPI.updateCarRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).updateCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.deleteCarByIdResponse GaragesClient.ServiceWebAPI.GarageWebAPI.deleteCarById(GaragesClient.ServiceWebAPI.deleteCarByIdRequest request) {
            return base.Channel.deleteCarById(request);
        }
        
        public void deleteCarById(long arg0) {
            GaragesClient.ServiceWebAPI.deleteCarByIdRequest inValue = new GaragesClient.ServiceWebAPI.deleteCarByIdRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.deleteCarByIdResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).deleteCarById(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteCarByIdResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.deleteCarByIdAsync(GaragesClient.ServiceWebAPI.deleteCarByIdRequest request) {
            return base.Channel.deleteCarByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteCarByIdResponse> deleteCarByIdAsync(long arg0) {
            GaragesClient.ServiceWebAPI.deleteCarByIdRequest inValue = new GaragesClient.ServiceWebAPI.deleteCarByIdRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).deleteCarByIdAsync(inValue);
        }
        
        public void deleteAllCars() {
            base.Channel.deleteAllCars();
        }
        
        public System.Threading.Tasks.Task deleteAllCarsAsync() {
            return base.Channel.deleteAllCarsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.persistOwnerResponse GaragesClient.ServiceWebAPI.GarageWebAPI.persistOwner(GaragesClient.ServiceWebAPI.persistOwnerRequest request) {
            return base.Channel.persistOwner(request);
        }
        
        public string persistOwner(GaragesClient.ServiceWebAPI.ownerDto arg0) {
            GaragesClient.ServiceWebAPI.persistOwnerRequest inValue = new GaragesClient.ServiceWebAPI.persistOwnerRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.persistOwnerResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).persistOwner(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistOwnerResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.persistOwnerAsync(GaragesClient.ServiceWebAPI.persistOwnerRequest request) {
            return base.Channel.persistOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistOwnerResponse> persistOwnerAsync(GaragesClient.ServiceWebAPI.ownerDto arg0) {
            GaragesClient.ServiceWebAPI.persistOwnerRequest inValue = new GaragesClient.ServiceWebAPI.persistOwnerRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).persistOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.findOwnerByIdResponse GaragesClient.ServiceWebAPI.GarageWebAPI.findOwnerById(GaragesClient.ServiceWebAPI.findOwnerByIdRequest request) {
            return base.Channel.findOwnerById(request);
        }
        
        public GaragesClient.ServiceWebAPI.ownerDto findOwnerById(long arg0) {
            GaragesClient.ServiceWebAPI.findOwnerByIdRequest inValue = new GaragesClient.ServiceWebAPI.findOwnerByIdRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.findOwnerByIdResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findOwnerById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findOwnerByIdResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.findOwnerByIdAsync(GaragesClient.ServiceWebAPI.findOwnerByIdRequest request) {
            return base.Channel.findOwnerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findOwnerByIdResponse> findOwnerByIdAsync(long arg0) {
            GaragesClient.ServiceWebAPI.findOwnerByIdRequest inValue = new GaragesClient.ServiceWebAPI.findOwnerByIdRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findOwnerByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.findAllOwnersResponse GaragesClient.ServiceWebAPI.GarageWebAPI.findAllOwners(GaragesClient.ServiceWebAPI.findAllOwnersRequest request) {
            return base.Channel.findAllOwners(request);
        }
        
        public GaragesClient.ServiceWebAPI.ownerDto[] findAllOwners() {
            GaragesClient.ServiceWebAPI.findAllOwnersRequest inValue = new GaragesClient.ServiceWebAPI.findAllOwnersRequest();
            GaragesClient.ServiceWebAPI.findAllOwnersResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findAllOwners(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllOwnersResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.findAllOwnersAsync(GaragesClient.ServiceWebAPI.findAllOwnersRequest request) {
            return base.Channel.findAllOwnersAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllOwnersResponse> findAllOwnersAsync() {
            GaragesClient.ServiceWebAPI.findAllOwnersRequest inValue = new GaragesClient.ServiceWebAPI.findAllOwnersRequest();
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findAllOwnersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.findAllGaragesResponse GaragesClient.ServiceWebAPI.GarageWebAPI.findAllGarages(GaragesClient.ServiceWebAPI.findAllGaragesRequest request) {
            return base.Channel.findAllGarages(request);
        }
        
        public GaragesClient.ServiceWebAPI.garageDto[] findAllGarages() {
            GaragesClient.ServiceWebAPI.findAllGaragesRequest inValue = new GaragesClient.ServiceWebAPI.findAllGaragesRequest();
            GaragesClient.ServiceWebAPI.findAllGaragesResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findAllGarages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllGaragesResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.findAllGaragesAsync(GaragesClient.ServiceWebAPI.findAllGaragesRequest request) {
            return base.Channel.findAllGaragesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.findAllGaragesResponse> findAllGaragesAsync() {
            GaragesClient.ServiceWebAPI.findAllGaragesRequest inValue = new GaragesClient.ServiceWebAPI.findAllGaragesRequest();
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).findAllGaragesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.updateGarageResponse GaragesClient.ServiceWebAPI.GarageWebAPI.updateGarage(GaragesClient.ServiceWebAPI.updateGarageRequest request) {
            return base.Channel.updateGarage(request);
        }
        
        public string updateGarage(GaragesClient.ServiceWebAPI.garageDto arg0) {
            GaragesClient.ServiceWebAPI.updateGarageRequest inValue = new GaragesClient.ServiceWebAPI.updateGarageRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.updateGarageResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).updateGarage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateGarageResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.updateGarageAsync(GaragesClient.ServiceWebAPI.updateGarageRequest request) {
            return base.Channel.updateGarageAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.updateGarageResponse> updateGarageAsync(GaragesClient.ServiceWebAPI.garageDto arg0) {
            GaragesClient.ServiceWebAPI.updateGarageRequest inValue = new GaragesClient.ServiceWebAPI.updateGarageRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).updateGarageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.persistCarResponse GaragesClient.ServiceWebAPI.GarageWebAPI.persistCar(GaragesClient.ServiceWebAPI.persistCarRequest request) {
            return base.Channel.persistCar(request);
        }
        
        public string persistCar(GaragesClient.ServiceWebAPI.carDto arg0) {
            GaragesClient.ServiceWebAPI.persistCarRequest inValue = new GaragesClient.ServiceWebAPI.persistCarRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.persistCarResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).persistCar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistCarResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.persistCarAsync(GaragesClient.ServiceWebAPI.persistCarRequest request) {
            return base.Channel.persistCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistCarResponse> persistCarAsync(GaragesClient.ServiceWebAPI.carDto arg0) {
            GaragesClient.ServiceWebAPI.persistCarRequest inValue = new GaragesClient.ServiceWebAPI.persistCarRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).persistCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.persistGarageResponse GaragesClient.ServiceWebAPI.GarageWebAPI.persistGarage(GaragesClient.ServiceWebAPI.persistGarageRequest request) {
            return base.Channel.persistGarage(request);
        }
        
        public string persistGarage(GaragesClient.ServiceWebAPI.garageDto arg0) {
            GaragesClient.ServiceWebAPI.persistGarageRequest inValue = new GaragesClient.ServiceWebAPI.persistGarageRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.persistGarageResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).persistGarage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistGarageResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.persistGarageAsync(GaragesClient.ServiceWebAPI.persistGarageRequest request) {
            return base.Channel.persistGarageAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.persistGarageResponse> persistGarageAsync(GaragesClient.ServiceWebAPI.garageDto arg0) {
            GaragesClient.ServiceWebAPI.persistGarageRequest inValue = new GaragesClient.ServiceWebAPI.persistGarageRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).persistGarageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.deleteGarageByIdResponse GaragesClient.ServiceWebAPI.GarageWebAPI.deleteGarageById(GaragesClient.ServiceWebAPI.deleteGarageByIdRequest request) {
            return base.Channel.deleteGarageById(request);
        }
        
        public void deleteGarageById(long arg0) {
            GaragesClient.ServiceWebAPI.deleteGarageByIdRequest inValue = new GaragesClient.ServiceWebAPI.deleteGarageByIdRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.deleteGarageByIdResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).deleteGarageById(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteGarageByIdResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.deleteGarageByIdAsync(GaragesClient.ServiceWebAPI.deleteGarageByIdRequest request) {
            return base.Channel.deleteGarageByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteGarageByIdResponse> deleteGarageByIdAsync(long arg0) {
            GaragesClient.ServiceWebAPI.deleteGarageByIdRequest inValue = new GaragesClient.ServiceWebAPI.deleteGarageByIdRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).deleteGarageByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.deleteOwnerByIdResponse GaragesClient.ServiceWebAPI.GarageWebAPI.deleteOwnerById(GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest request) {
            return base.Channel.deleteOwnerById(request);
        }
        
        public void deleteOwnerById(long arg0) {
            GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest inValue = new GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest();
            inValue.arg0 = arg0;
            GaragesClient.ServiceWebAPI.deleteOwnerByIdResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).deleteOwnerById(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteOwnerByIdResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.deleteOwnerByIdAsync(GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest request) {
            return base.Channel.deleteOwnerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.deleteOwnerByIdResponse> deleteOwnerByIdAsync(long arg0) {
            GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest inValue = new GaragesClient.ServiceWebAPI.deleteOwnerByIdRequest();
            inValue.arg0 = arg0;
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).deleteOwnerByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GaragesClient.ServiceWebAPI.getInfoTotalResponse GaragesClient.ServiceWebAPI.GarageWebAPI.getInfoTotal(GaragesClient.ServiceWebAPI.getInfoTotalRequest request) {
            return base.Channel.getInfoTotal(request);
        }
        
        public GaragesClient.ServiceWebAPI.infoTotalDto[] getInfoTotal() {
            GaragesClient.ServiceWebAPI.getInfoTotalRequest inValue = new GaragesClient.ServiceWebAPI.getInfoTotalRequest();
            GaragesClient.ServiceWebAPI.getInfoTotalResponse retVal = ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).getInfoTotal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.getInfoTotalResponse> GaragesClient.ServiceWebAPI.GarageWebAPI.getInfoTotalAsync(GaragesClient.ServiceWebAPI.getInfoTotalRequest request) {
            return base.Channel.getInfoTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<GaragesClient.ServiceWebAPI.getInfoTotalResponse> getInfoTotalAsync() {
            GaragesClient.ServiceWebAPI.getInfoTotalRequest inValue = new GaragesClient.ServiceWebAPI.getInfoTotalRequest();
            return ((GaragesClient.ServiceWebAPI.GarageWebAPI)(this)).getInfoTotalAsync(inValue);
        }
        
        public void deleteAllOwners() {
            base.Channel.deleteAllOwners();
        }
        
        public System.Threading.Tasks.Task deleteAllOwnersAsync() {
            return base.Channel.deleteAllOwnersAsync();
        }
    }
}
